package com.techconsulting.lending.service;
import com.techconsulting.lending.domain.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.beans.factory.annotation.Value; import org.springframework.stereotype.Service; import java.math.*; import java.time.*; import java.time.temporal.ChronoUnit;
@Service
public class LoanCalculationService {
 private static final BigDecimal ZERO=BigDecimal.ZERO.setScale(2); private final Clock clock; private final boolean npaOnDpd;
 @Autowired public LoanCalculationService(@Value("${app.npa-on-dpd-over-seven:false}") boolean npaOnDpd){this(Clock.systemUTC(),npaOnDpd);} LoanCalculationService(Clock c,boolean d){clock=c;npaOnDpd=d;}
 public ManualLending calculate(Long userId,Long batchId,LoanReportStaging row,ManualLending target){
  BigDecimal invested=money(row.getInvestedAmount()), received=money(row.getAmountReceived()); int tenure=row.getTenure().intValueExact(); if(invested.signum()<=0||tenure<=0||received.signum()<0) throw new IllegalArgumentException("Invested amount and tenure must be positive; received amount cannot be negative");
  BigDecimal emi=invested.divide(BigDecimal.valueOf(tenure),2,RoundingMode.HALF_UP); BigDecimal completed=received.divideToIntegralValue(emi); BigDecimal estimatedPrincipal=completed.multiply(emi).min(invested).setScale(2,RoundingMode.HALF_UP); BigDecimal principal=row.getReportedPrincipalReceived()==null?estimatedPrincipal:money(row.getReportedPrincipalReceived()).min(invested); BigDecimal interest=row.getReportedInterestReceived()==null?received.subtract(principal).setScale(2,RoundingMode.HALF_UP):money(row.getReportedInterestReceived()); BigDecimal outstanding=invested.subtract(principal).max(ZERO); String reportStatus=row.getLoanStatus().trim().toUpperCase(); boolean closed="CLOSED".equals(reportStatus); BigDecimal ret=closed?received.subtract(invested):interest; BigDecimal retPct=ret.multiply(BigDecimal.valueOf(100)).divide(invested,4,RoundingMode.HALF_UP);
  LocalDate today=LocalDate.now(clock);BigDecimal previousReceived=target.getAmountReceived();LocalDate lastPayment=target.getLastEmiPaidOn();if(received.signum()>0&&(previousReceived==null||received.compareTo(previousReceived)>0))lastPayment=today;if(lastPayment==null)lastPayment=row.getInvestmentDate();
  target.setUserId(userId);target.setSchemeId(row.getSchemeId());target.setLoanId(row.getLoanId());target.setBorrowerName(row.getBorrowerName());target.setInvestedAmount(invested);target.setTenureMonths(tenure);target.setPrincipalEmi(emi);target.setAmountReceived(received);target.setCalculatedPrincipalReceived(principal);target.setCalculatedInterestReceived(interest);target.setOutstandingPrincipal(outstanding);target.setMarketValue(closed?received:invested.add(interest));target.setReturnAmount(ret);target.setReturnPercentage(retPct);target.setInvestmentDate(row.getInvestmentDate());target.setLastEmiPaidOn(lastPayment);target.setExpectedMaturityDate(row.getInvestmentDate().plusMonths(tenure));target.setLoanStatus(reportStatus);target.setInvestmentStatus(received.compareTo(invested)>0?"SOLD":"NOT_SOLD");target.setDpd(row.getDpd()==null?0:row.getDpd());target.setSourceImportBatchId(batchId);
  boolean npa=false;String reason=null;if("NPA".equals(reportStatus)){npa=true;reason="REPORTED_AS_NPA";} else if(closed&&received.compareTo(invested)<0){npa=true;reason="CLOSED_BEFORE_PRINCIPAL_RECOVERY";} else if(today.isAfter(target.getExpectedMaturityDate())&&outstanding.signum()>0){npa=true;reason="TENURE_EXCEEDED";} else if(!closed&&received.compareTo(emi)<0&&ChronoUnit.DAYS.between(lastPayment,today)>35){npa=true;reason="NO_EMI_OVER_35_DAYS";} else if(npaOnDpd&&target.getDpd()>7){npa=true;reason="DPD_OVER_7";} target.setNpa(npa);target.setNpaReason(reason);target.setComments(npa?reason:(target.getDpd()>7?"DPD is "+target.getDpd():null)); return target;
 }
 private BigDecimal money(BigDecimal v){return (v==null?BigDecimal.ZERO:v).setScale(2,RoundingMode.HALF_UP);}
}
