CREATE TABLE lumpsum_repayment (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    reconciliation_account_id BIGINT NULL,
    payment_notification_id BIGINT NOT NULL,
    bank_payment_notification_id BIGINT NULL,
    processing_date DATE NOT NULL,
    principal_amount DECIMAL(19,2) NOT NULL,
    interest_amount DECIMAL(19,2) NOT NULL,
    total_amount DECIMAL(19,2) NOT NULL,
    lender_reported_amount DECIMAL(19,2) NOT NULL,
    bank_credit_amount DECIMAL(19,2) NULL,
    difference_amount DECIMAL(19,2) NULL,
    subject_validation_status VARCHAR(30) NOT NULL,
    bank_validation_status VARCHAR(30) NOT NULL,
    validation_error VARCHAR(1000) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT uk_lumpsum_notification UNIQUE (payment_notification_id),
    CONSTRAINT fk_lumpsum_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_lumpsum_account FOREIGN KEY (reconciliation_account_id) REFERENCES email_reconciliation_account(id),
    CONSTRAINT fk_lumpsum_payment FOREIGN KEY (payment_notification_id) REFERENCES payment_notification(id),
    CONSTRAINT fk_lumpsum_bank_payment FOREIGN KEY (bank_payment_notification_id) REFERENCES payment_notification(id),
    INDEX ix_lumpsum_user_date (user_id, processing_date),
    INDEX ix_lumpsum_bank_status (user_id, bank_validation_status)
);
