CREATE TABLE users (id BIGINT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(80) NOT NULL UNIQUE, email VARCHAR(190) NOT NULL UNIQUE, password_hash VARCHAR(100) NOT NULL, enabled BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE roles (id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(30) NOT NULL UNIQUE);
CREATE TABLE user_roles (user_id BIGINT NOT NULL, role_id BIGINT NOT NULL, PRIMARY KEY(user_id,role_id), CONSTRAINT fk_ur_user FOREIGN KEY(user_id) REFERENCES users(id), CONSTRAINT fk_ur_role FOREIGN KEY(role_id) REFERENCES roles(id));
INSERT INTO roles(name) VALUES ('ROLE_USER'),('ROLE_ADMIN');

CREATE TABLE import_batch (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT NOT NULL, report_type VARCHAR(40) NOT NULL, original_file_name VARCHAR(255) NOT NULL, file_checksum CHAR(64) NOT NULL, file_size BIGINT NOT NULL, status VARCHAR(30) NOT NULL, total_rows INT NOT NULL DEFAULT 0, valid_rows INT NOT NULL DEFAULT 0, invalid_rows INT NOT NULL DEFAULT 0, inserted_rows INT NOT NULL DEFAULT 0, updated_rows INT NOT NULL DEFAULT 0, skipped_rows INT NOT NULL DEFAULT 0, failed_rows INT NOT NULL DEFAULT 0, started_at TIMESTAMP NULL, completed_at TIMESTAMP NULL, error_message TEXT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT uk_import UNIQUE(user_id,report_type,file_checksum), CONSTRAINT fk_batch_user FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE loan_report_staging (id BIGINT AUTO_INCREMENT PRIMARY KEY, import_batch_id BIGINT NOT NULL, source_row_number INT NOT NULL, raw_row_json JSON NOT NULL, scheme_id VARCHAR(100), loan_id VARCHAR(100), borrower_name VARCHAR(200), loan_type VARCHAR(80), tenure DECIMAL(10,2), tenure_type VARCHAR(30), invested_amount DECIMAL(19,2), loan_amount DECIMAL(19,2), amount_received DECIMAL(19,2), expected_amount DECIMAL(19,2), remaining_amount DECIMAL(19,2), borrower_apr_percent DECIMAL(8,4), receivable_apr_percent DECIMAL(8,4), investment_date DATE, loan_status VARCHAR(30), dpd INT, source VARCHAR(80), facilitation_fee DECIMAL(19,2), collection_charges DECIMAL(19,2), recovery_fee DECIMAL(19,2), risk VARCHAR(50), lenden_score VARCHAR(50), validation_status VARCHAR(20) NOT NULL, validation_errors TEXT, processing_status VARCHAR(20) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, processed_at TIMESTAMP NULL, CONSTRAINT uk_stage_row UNIQUE(import_batch_id,source_row_number), CONSTRAINT fk_stage_batch FOREIGN KEY(import_batch_id) REFERENCES import_batch(id));
CREATE TABLE manual_lending (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT NOT NULL, scheme_id VARCHAR(100) NOT NULL, loan_id VARCHAR(100), borrower_name VARCHAR(200), invested_amount DECIMAL(19,2) NOT NULL, tenure_months INT NOT NULL, principal_emi DECIMAL(19,2) NOT NULL, amount_received DECIMAL(19,2) NOT NULL, calculated_principal_received DECIMAL(19,2) NOT NULL, calculated_interest_received DECIMAL(19,2) NOT NULL, market_value DECIMAL(19,2) NOT NULL, return_amount DECIMAL(19,2) NOT NULL, return_percentage DECIMAL(12,4) NOT NULL, outstanding_principal DECIMAL(19,2) NOT NULL, investment_date DATE NOT NULL, last_emi_paid_on DATE, expected_maturity_date DATE, loan_status VARCHAR(30) NOT NULL, investment_status VARCHAR(30) NOT NULL, dpd INT NOT NULL DEFAULT 0, is_npa BOOLEAN NOT NULL DEFAULT FALSE, npa_reason VARCHAR(80), comments TEXT, source_import_batch_id BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, version BIGINT NOT NULL DEFAULT 0, CONSTRAINT uk_manual_loan UNIQUE(user_id,scheme_id), INDEX ix_manual_status(user_id,loan_status), INDEX ix_manual_date(user_id,investment_date), CONSTRAINT fk_manual_user FOREIGN KEY(user_id) REFERENCES users(id), CONSTRAINT fk_manual_batch FOREIGN KEY(source_import_batch_id) REFERENCES import_batch(id));
CREATE TABLE wallet_transaction (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT NOT NULL, external_transaction_reference VARCHAR(160), row_fingerprint CHAR(64) NOT NULL, transaction_date DATE NOT NULL, transaction_type VARCHAR(40) NOT NULL, amount DECIMAL(19,2) NOT NULL, running_balance DECIMAL(19,2), description VARCHAR(1000), source_import_batch_id BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT uk_wallet_fp UNIQUE(user_id,row_fingerprint), INDEX ix_wallet_date(user_id,transaction_date), CONSTRAINT fk_wallet_user FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE bank_credit (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT NOT NULL, bank_transaction_reference VARCHAR(160), row_fingerprint CHAR(64) NOT NULL, transaction_date DATE NOT NULL, amount DECIMAL(19,2) NOT NULL, description VARCHAR(1000), source VARCHAR(60), source_import_batch_id BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT uk_bank_fp UNIQUE(user_id,row_fingerprint), CONSTRAINT fk_bank_user FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE payment_notification (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT NOT NULL, email_message_id VARCHAR(255) NOT NULL, email_received_at TIMESTAMP NOT NULL, sender VARCHAR(255), subject VARCHAR(500), notification_date DATE, reported_amount DECIMAL(19,2), notification_type VARCHAR(40) NOT NULL, raw_email_text TEXT, parsing_status VARCHAR(30) NOT NULL, parsing_error TEXT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT uk_email UNIQUE(user_id,email_message_id), CONSTRAINT fk_notification_user FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE reconciliation_record (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT NOT NULL, reconciliation_date DATE NOT NULL, lender_reported_amount DECIMAL(19,2), wallet_transaction_amount DECIMAL(19,2), withdrawal_amount DECIMAL(19,2), bank_credited_amount DECIMAL(19,2), difference_amount DECIMAL(19,2) NOT NULL, status VARCHAR(50) NOT NULL, reason VARCHAR(1000), payment_notification_id BIGINT, wallet_transaction_id BIGINT, bank_credit_id BIGINT, manually_resolved BOOLEAN NOT NULL DEFAULT FALSE, resolution_comment VARCHAR(1000), resolved_by VARCHAR(80), resolved_at TIMESTAMP NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX ix_recon_status(user_id,status), CONSTRAINT fk_recon_user FOREIGN KEY(user_id) REFERENCES users(id));
